proc xml_attr {text name {default ""}} {
    set pattern [format {%s="([^"]*)"} $name]
    if {[regexp $pattern $text -> value]} {
        return $value
    }
    return $default
}

proc board_part_file {board_part} {
    set parts [get_board_parts -quiet $board_part]
    if {[llength $parts] == 0} {
        fail "Board part '$board_part' is not installed. Install the board files or set BOARD_CONSTRAINTS=0."
    }
    set file_name [get_property FILE_NAME [lindex $parts 0]]
    if {$file_name eq "" || ![file exists $file_name]} {
        fail "Could not resolve board.xml for board part '$board_part'."
    }
    return [file normalize $file_name]
}

proc board_part_pin_file {board_xml} {
    set fh [open $board_xml r]
    set data [read $fh]
    close $fh

    foreach line [split $data "\n"] {
        if {[string match {*<component*name="part0"*type="fpga"*} $line] ||
            [string match {*<component*type="fpga"*name="part0"*} $line]} {
            set pin_file [xml_attr $line pin_map_file]
            if {$pin_file ne ""} {
                return [file normalize [file join [file dirname $board_xml] $pin_file]]
            }
        }
    }

    set fallback [file normalize [file join [file dirname $board_xml] part0_pins.xml]]
    if {[file exists $fallback]} {
        return $fallback
    }
    fail "Could not find part0 pin map referenced by $board_xml."
}

proc board_clock_frequency {board_xml interface_name default_frequency} {
    set fh [open $board_xml r]
    set data [read $fh]
    close $fh

    set in_interface 0
    foreach line [split $data "\n"] {
        if {[string match "*<interface*name=\"$interface_name\"*" $line]} {
            set in_interface 1
        }
        if {$in_interface && [string match {*<parameter*name="frequency"*} $line]} {
            set value [xml_attr $line value]
            if {$value ne ""} {
                return $value
            }
        }
        if {$in_interface && [string match {*</interface>*} $line]} {
            set in_interface 0
        }
    }
    return $default_frequency
}

proc board_pin_db {pin_xml} {
    if {![file exists $pin_xml]} {
        fail "Board pin map not found: $pin_xml"
    }

    set pins [dict create]
    set fh [open $pin_xml r]
    set data [read $fh]
    close $fh

    foreach line [split $data "\n"] {
        if {![regexp {<pin[[:space:]]} $line]} {
            continue
        }
        set name [xml_attr $line name]
        if {$name eq ""} {
            continue
        }
        set props [dict create]
        foreach attr {loc iostandard drive slew dqs_bias} {
            set value [xml_attr $line $attr]
            if {$value ne ""} {
                dict set props $attr $value
            }
        }
        dict set pins $name $props
    }

    return $pins
}

proc require_board_pin {pins name} {
    if {![dict exists $pins $name]} {
        fail "Board pin '$name' is missing from installed board pin map."
    }
    return [dict get $pins $name]
}

proc emit_port_pin_constraint {fh pins board_pin port {iostandard_mode BOARD}} {
    set props [require_board_pin $pins $board_pin]
    if {![dict exists $props loc]} {
        fail "Board pin '$board_pin' has no loc property."
    }

    puts $fh "## $port <= $board_pin"
    puts $fh "set_property PACKAGE_PIN [dict get $props loc] \[get_ports {$port}\]"

    set io ""
    if {$iostandard_mode eq "BOARD"} {
        if {[dict exists $props iostandard]} {
            set io [dict get $props iostandard]
        }
    } elseif {$iostandard_mode ne "" && $iostandard_mode ne "NONE"} {
        set io $iostandard_mode
    }
    if {$io ne ""} {
        puts $fh "set_property IOSTANDARD $io \[get_ports {$port}\]"
    }

    if {[dict exists $props drive]} {
        puts $fh "set_property DRIVE [dict get $props drive] \[get_ports {$port}\]"
    }
    if {[dict exists $props slew]} {
        puts $fh "set_property SLEW [dict get $props slew] \[get_ports {$port}\]"
    }
    puts $fh ""
}

proc generate_as02mc04_board_xdc {c} {
    set board_xml [board_part_file [dict get $c board_part]]
    set pin_xml [board_part_pin_file $board_xml]
    set pins [board_pin_db $pin_xml]

    set out_dir [file join [dict get $c build] generated]
    ensure_dir $out_dir
    set xdc [file join $out_dir as02mc04_board.xdc]

    set clk_freq [board_clock_frequency $board_xml diff_100mhz_clk 100000000]
    set clk_period [format %.3f [expr {1000000000.0 / double($clk_freq)}]]
    set led_iostandard [dict get $c led_iostandard]

    set fh [open $xdc w]
    puts $fh "## Generated by scripts/board_constraints.tcl."
    puts $fh "## Source board file: $board_xml"
    puts $fh "## Source pin map: $pin_xml"
    puts $fh "## Do not edit this file; edit board files or Tcl mapping instead."
    puts $fh ""

    puts $fh "## 100 MHz differential system clock from board interface diff_100mhz_clk."
    emit_port_pin_constraint $fh $pins diff_100mhz_clk_p clk_100mhz_p BOARD
    emit_port_pin_constraint $fh $pins diff_100mhz_clk_n clk_100mhz_n BOARD
    puts $fh "create_clock -period $clk_period -name clk_100mhz \[get_ports clk_100mhz_p\]"
    puts $fh ""

    puts $fh "## User LEDs from board interface led_7bits."
    puts $fh "## LED_IOSTANDARD=$led_iostandard; use LED_IOSTANDARD=NONE to omit it or override with e.g. LVCMOS33."
    emit_port_pin_constraint $fh $pins GPIO_LED_R {led[0]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_G {led[1]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_H {led[2]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_1 {led[3]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_2 {led[4]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_3 {led[5]} $led_iostandard
    emit_port_pin_constraint $fh $pins GPIO_LED_4 {led[6]} $led_iostandard
    close $fh

    puts "Generated board constraints: $xdc"
    return $xdc
}
